FROM openjdk:8

RUN apt-get update \
    && apt-get install -y --no-install-recommends tzdata
    
RUN TZ=Asia/Taipei \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

ARG WAR_FILE=build/libs/*.war
COPY ${WAR_FILE} SpringOAuth2Test.war
ENTRYPOINT ["java","-jar","/SpringOAuth2Test.war"]